FROM golang:1.17.2-bullseye
WORKDIR /go/src/app

RUN apt-get update && apt-get install -y \
    poppler-utils \
    tesseract-ocr-spa \
    && rm -rf /var/lib/apt/lists/*
COPY extracttext/go.mod extracttext/go.sum ./
COPY ./shared /go/src/shared
RUN go mod download

COPY ./extracttext .

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["extracttext"]
