FROM golang:1.17

WORKDIR /go/src/app

COPY crawler/go.mod crawler/go.sum ./
COPY ./shared /go/src/shared
RUN go mod download

COPY ./fetcher .

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["fetcher"]
